// Generates docs/*.md from the rules.
//
// The markdown is an OUTPUT, never a source. It exists so a rule can be
// linked, reviewed and archived outside this repository — in a ticket, in a
// technical file, in an audit trail. Editing it by hand would recreate
// exactly the drift this whole structure avoids, so every generated file
// says so at the top.
//
//   node export-docs.mjs

import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { selectionControl } from './rules/selection.js';
import { conditionalDisclosure } from './rules/disclosure.js';
import { nameTruncation } from './rules/names.js';

// A literal pipe inside a table cell ends the cell. The return type of the
// selection rule is a union written with pipes, so without this the table
// silently collapses into the wrong number of columns.
const cell = (text) => String(text).replace(/\|/g, '\\|');

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'docs');

const RULES = [selectionControl, conditionalDisclosure, nameTruncation];

function render(rule) {
  return `<!-- GENERATED by export-docs.mjs — do not edit.
     Source: rules/${rule.id.split('/')[0]}.js -->

# ${rule.title}

> ${rule.rule}

${rule.contract ? `## What you get

| | |
|---|---|
| **Takes** | \`${cell(rule.contract.input)}\` |
| **Returns** | \`${cell(rule.contract.returns)}\` |

| You get | You render |
|---|---|
${rule.contract.wiring.map(([v, what]) => `| \`${cell(v)}\` | ${cell(what)} |`).join('\n')}
${rule.contract.note ? `\n${rule.contract.note}\n` : ''}
` : ''}## Rationale

${rule.rationale}

## Edge cases

${rule.edgeCases.map((e) => `### ${e.case}\n\n${e.handling}`).join('\n\n')}

## Open questions

These are not oversights. They are what the specification leaves undecided —
recorded so they can be answered rather than quietly assumed.

${rule.openQuestions.map((q) => `- ${q}`).join('\n')}

${rule.strategies ? `## Options considered

All three are selectable in the prototype's control panel, including the
rejected one — a reason that can be run is worth more than one that has to be
believed.

${Object.entries(rule.strategies).map(([, v]) => `### ${v.label} — ${v.status}\n\n${v.short}\n\n${v.why}`).join('\n\n')}

` : ''}${rule.ladder ? `## The ladder

Tried in order; the first rung that fits wins.

${rule.ladder.map((r, i) => `${i + 1}. \`${r.step}\` — ${r.description}`).join('\n')}

` : ''}${rule.conditions ? `## Conditions

| Field | Shown when | Reads |
|---|---|---|
${rule.conditions.map((c) => `| \`${c.field}\` — ${c.label} | ${c.when} | \`${c.dependsOn}\` |`).join('\n')}

Always present: ${rule.baseFields.map((f) => `\`${f}\``).join(', ')}

` : ''}## Provenance

| Date | Change | By | Basis |
|---|---|---|---|
${rule.provenance.map((p) => `| ${p.date} | ${p.change} | ${p.by} | ${p.basis} |`).join('\n')}

## Logic

\`\`\`js
${rule.threshold != null ? `const THRESHOLD = ${rule.threshold};\n\n` : ''}${rule.apply.toString()
  .replace(/^apply/, rule.threshold != null ? 'function controlType' : 'function visibleFields')
  .replace(/this\.threshold/g, 'THRESHOLD')
  .replace(/this\.conditions/g, 'CONDITIONS')}
\`\`\`
`;
}

await mkdir(outDir, { recursive: true });

for (const rule of RULES) {
  const name = `${rule.id.replace('/', '-')}.md`;
  await writeFile(join(outDir, name), render(rule), 'utf8');
  console.log(`docs/${name}`);
}
