// Generates docs/*.md from the rules.
//
// The markdown is an OUTPUT, never a source. It exists so a rule can be
// linked, reviewed and archived outside this repository — in a ticket, in a
// technical file, in an audit trail. Editing it by hand would recreate
// exactly the drift this whole structure avoids, so every generated file
// says so at the top.
//
//   node export-docs.mjs

import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { selectionControl } from './rules/selection.js';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'docs');

const RULES = [selectionControl];

function render(rule) {
  return `<!-- GENERATED by export-docs.mjs — do not edit.
     Source: rules/${rule.id.split('/')[0]}.js -->

# ${rule.title}

> ${rule.rule}

## Rationale

${rule.rationale}

## Edge cases

${rule.edgeCases.map((e) => `### ${e.case}\n\n${e.handling}`).join('\n\n')}

## Open questions

These are not oversights. They are what the specification leaves undecided —
recorded so they can be answered rather than quietly assumed.

${rule.openQuestions.map((q) => `- ${q}`).join('\n')}

## Provenance

| Date | Change | By | Basis |
|---|---|---|---|
${rule.provenance.map((p) => `| ${p.date} | ${p.change} | ${p.by} | ${p.basis} |`).join('\n')}

## Logic

\`\`\`js
const THRESHOLD = ${rule.threshold};

${rule.apply.toString()
  .replace(/^apply/, 'function controlType')
  .replace(/this\.threshold/g, 'THRESHOLD')}
\`\`\`
`;
}

await mkdir(outDir, { recursive: true });

for (const rule of RULES) {
  const name = `${rule.id.replace('/', '-')}.md`;
  await writeFile(join(outDir, name), render(rule), 'utf8');
  console.log(`docs/${name}`);
}
